Repository librosa/librosa, pull requests merged in 2018-11, with the labels that each got.

#777 Include LICENSE.md in sdists
  MANIFEST.in
Labels: management

#766 made smoothing optional, allowed overriding smoothing window function
  docs/examples/plot_chroma.py
  librosa/feature/spectral.py
Labels: API change, Hacktoberfest, enhancement, functionality

#775 fix failing test CI's / migrate to pytest
  .travis.yml
  .travis_dependencies.sh
  CONTRIBUTING.md
  appveyor.yml
  librosa/segment.py
  setup.cfg
  setup.py
  tests/README.md
  tests/mpl_ic.py
  tests/test_beat.py
  tests/test_cache.py
  tests/test_constantq.py
  tests/test_core.py
  tests/test_decompose.py
  tests/test_display.py
  tests/test_dtw.py
  tests/test_effects.py
  tests/test_failures.py
  tests/test_features.py
  tests/test_filters.py
  tests/test_met_features.py
  tests/test_onset.py
  tests/test_output.py
  tests/test_segment.py
  tests/test_sequence.py
  tests/test_time_frequency.py
  tests/test_util.py
Labels: Upstream/dependency bug, enhancement, testing

#785 Remove asserts
  librosa/core/audio.py
  librosa/core/spectrum.py
  tests/test_core.py
Labels: bug, enhancement, management, testing

#790 Dropped imp for importlib
  docs/conf.py
  librosa/version.py
  setup.py
Labels: management

#791 Updated docs and docstring around write_wav
  docs/ioformats.rst
  librosa/output.py
Labels: documentation
