Repository librosa/librosa, pull requests merged in 2018-02, with the labels that each got.

#663 fixed #657 by reimplementing the delta function. Deprecates trim=
  librosa/feature/utils.py
  setup.py
  tests/test_features.py
Labels: API change, bug, enhancement, functionality

#666 updated load docs for sampling rate. fixes #659 [ci skip]
  librosa/core/audio.py
Labels: documentation

#435 [CR] Inverse CQT
  librosa/core/constantq.py
  librosa/core/spectrum.py
  librosa/filters.py
  tests/test_constantq.py
Labels: Hacktoberfest, enhancement, functionality

#671 Add warnings when phase is lost
  librosa/core/spectrum.py
Labels: enhancement

#673 fixed #672 by making delta width message more explicit
  librosa/feature/utils.py
Labels: enhancement

#674 updated write_wav/output docs to point to soundfile. fixes #640 [ci s…
  docs/conf.py
  librosa/output.py
Labels: documentation

#677 Added appveyor configuration
  README.md
  appveyor.yml
  librosa/util/files.py
  tests/test_beat.py
  tests/test_core.py
  tests/test_decompose.py
  tests/test_display.py
  tests/test_effects.py
  tests/test_features.py
  tests/test_filters.py
  tests/test_met_features.py
  tests/test_onset.py
  tests/test_output.py
  tests/test_segment.py
  tests/test_util.py
Labels: bug, testing

#679 implemented PCEN. fixes #615. needs tests
  librosa/core/__init__.py
  librosa/core/spectrum.py
  tests/test_core.py
Labels: enhancement, functionality

#680 updated display tests to support mpl2.1
  .travis_dependencies.sh
  appveyor.yml
  setup.py
  tests/baseline_images/test_display/time_scales_auto.png
  tests/mpl_ic.py
  tests/test_display.py
Labels: testing

#682 Expanded MFCC options
  librosa/feature/spectral.py
  librosa/filters.py
  tests/test_features.py
Labels: API change, enhancement, functionality
