Repository librosa/librosa, pull requests merged in 2018-06, with the labels that each got.

#727 Update documentation of get_duration()
  librosa/core/audio.py
Labels: documentation

#730 Don't use the deprecated cachedir property of joblib Memory
  librosa/cache.py
  setup.py
Labels: API change, bug

#731 Fix a typo in time_frequency.py
  librosa/core/time_frequency.py
Labels: documentation

#735 fixes #717: adds times_like and samples_like
  librosa/core/__init__.py
  librosa/core/time_frequency.py
  tests/test_time_frequency.py
Labels: API change, enhancement, functionality
