Repository librosa/librosa, pull requests merged in 2019-06, with the labels that each got.

#892 stabler exponentiation in PCEN + logarithmic limit case
  librosa/core/spectrum.py
  tests/test_core.py
Labels: API change, enhancement, functionality

#901 time_stretch: STFT kwargs + ISTFT length trimming + doc
  librosa/effects.py
Labels: API change, bug, enhancement, functionality

#903 070 cleanups
  librosa/__init__.py
  librosa/feature/spectral.py
  librosa/version.py
  setup.py
Labels: documentation, management

#904 [CR needed] Cross similarity
  librosa/core/audio.py
  librosa/decompose.py
  librosa/segment.py
  librosa/sequence.py
  tests/.coveragerc
  tests/test_decompose.py
  tests/test_segment.py
Labels: enhancement, functionality

#898 [MRG] more efficient length trimming for inverters
  librosa/core/constantq.py
  librosa/core/spectrum.py
  tests/test_core.py
Labels: enhancement
