Repository librosa/librosa, pull requests merged in 2019-12, with the labels that each got.

#1021 temporary workaround for .load() with pathlib
  librosa/core/audio.py
Labels: enhancement

#1022 mu-law companding
  librosa/core/__init__.py
  librosa/core/audio.py
  tests/test_core.py
Labels: functionality

#1036 mu-law defaults
  librosa/core/audio.py
Labels: documentation, enhancement

#1038 remove ReST-LaTeX math in tfreassign doc
  librosa/core/spectrum.py
Labels: documentation

#1042 Update metric location
  librosa/sequence.py
Labels: documentation

#1041 Fix librosa.feature.rms #1040
  librosa/feature/spectral.py
  tests/test_features.py
Labels: bug

#1043 Reassignment docstring typos
  librosa/core/spectrum.py
Labels: documentation
