Repository librosa/librosa, pull requests merged in 2019-09, with the labels that each got.

#979 fixed #978, fft normalization in rms calculation
  librosa/feature/spectral.py
  tests/test_features.py
Labels: bug

#968 [WIP] check Fortran contiguity in valid_audio
  librosa/core/audio.py
  librosa/effects.py
  librosa/util/utils.py
  tests/test_failures.py
Labels: API change

#963 support more x_axis values in waveplot
  librosa/display.py
  tests/baseline_images/test_display/test_abs_input.png
  tests/baseline_images/test_display/test_chroma.png
  tests/baseline_images/test_display/test_complex_input.png
  tests/baseline_images/test_display/test_coords.png
  tests/baseline_images/test_display/test_cqt_hz.png
  tests/baseline_images/test_display/test_cqt_note.png
  tests/baseline_images/test_display/test_double_chroma.png
  tests/baseline_images/test_display/test_fourier_tempo.png
  tests/baseline_images/test_display/test_sharex_specshow_ms.png
  tests/baseline_images/test_display/test_sharex_waveplot_ms.png
  tests/baseline_images/test_display/test_specshow_ext_axes.png
  tests/baseline_images/test_display/test_tempo.png
  tests/baseline_images/test_display/test_time_scales_auto.png
  tests/baseline_images/test_display/test_time_unit.png
  tests/baseline_images/test_display/test_time_unit_lag.png
  tests/baseline_images/test_display/test_tonnetz.png
  tests/baseline_images/test_display/test_waveplot_ext_axes.png
  tests/baseline_images/test_display/test_waveplot_mono.png
  tests/baseline_images/test_display/test_waveplot_stereo.png
  tests/baseline_images/test_display/test_x_mel.png
  tests/baseline_images/test_display/test_xaxis_frames_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_lag_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_linear_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_log_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_frames.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_linear.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_log.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_time.png
  tests/baseline_images/test_display/test_xaxis_time_yaxis_lag.png
  tests/baseline_images/test_display/test_xaxis_time_yaxis_none.png
  tests/baseline_images/test_display/test_y_mel.png
  tests/baseline_images/test_display/test_y_mel_bounded.png
  tests/test_display.py
Labels: enhancement

#971 Beat and tempo priors
  librosa/beat.py
  tests/test_beat.py
Labels: enhancement, functionality
