Repository librosa/librosa, pull requests merged in 2019-08, with the labels that each got.

#933 Fix travis builds for py3.5
  .travis.yml
  .travis_dependencies.sh
Labels: management, testing

#930 CQT tuning correction, tuning standardization, deprecate A440=
  librosa/core/constantq.py
  librosa/core/spectrum.py
  librosa/core/time_frequency.py
  librosa/display.py
  librosa/feature/spectral.py
  librosa/filters.py
  tests/test_filters.py
  tests/test_time_frequency.py
Labels: API change, bug, documentation, enhancement, functionality

#934 CQT Griffin-Lim
  librosa/core/__init__.py
  librosa/core/constantq.py
  librosa/core/spectrum.py
  tests/test_constantq.py
Labels: enhancement, functionality

#920 Check boundary condition for non-subseq dtw
  librosa/sequence.py
  tests/test_dtw.py
Labels: enhancement, functionality

#926 [MRG] Time-frequency reassignment
  librosa/core/spectrum.py
  setup.py
  tests/test_core.py
Labels: enhancement, functionality

#939 sr kwarg in melspectrogram(stft(...)) docstring [ci skip]
  librosa/feature/spectral.py
Labels: documentation

#940 HTK-compatibility features: liftering and pre-emphasis
  librosa/effects.py
  librosa/feature/spectral.py
  tests/test_effects.py
  tests/test_features.py
Labels: API change, enhancement, functionality

#942 Add seek call after sf.info
  librosa/core/audio.py
  tests/test_core.py
Labels: bug

#949 Accelerated lag<->recurrence, util.shear, deprecated roll_sparse
  .travis_dependencies.sh
  docs/install.rst
  librosa/segment.py
  librosa/util/__init__.py
  librosa/util/utils.py
  setup.py
  tests/test_segment.py
  tests/test_util.py
Labels: enhancement

#950 Allow initial phase estimates for griffinlim methods
  librosa/core/constantq.py
  librosa/core/spectrum.py
  tests/test_constantq.py
  tests/test_core.py
Labels: API change, enhancement, functionality

#943 Improve STFT docstring [ci skip]
  librosa/core/spectrum.py
Labels: documentation

#953 Deprecated ifgram
  librosa/core/__init__.py
  librosa/core/harmonic.py
  librosa/core/spectrum.py
Labels: management

#957 times_like audit
  librosa/beat.py
  librosa/core/spectrum.py
  librosa/display.py
  librosa/onset.py
  librosa/sequence.py
  librosa/util/utils.py
Labels: documentation

#958 [DOC] visualization of time-frequency reassignment [ci skip]
  librosa/core/spectrum.py
Labels: documentation

#960 Ensure fortran-ordering of audio buffers after resampling
  librosa/core/audio.py
  setup.py
  tests/test_core.py
Labels: bug

#966 multidimensional framing and contiguous stacking
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/spectrum.py
  librosa/display.py
  librosa/feature/utils.py
  librosa/util/__init__.py
  librosa/util/utils.py
  tests/baseline_images/test_display/test_sharex_specshow_ms.png
  tests/baseline_images/test_display/test_sharex_waveplot_ms.png
  tests/baseline_images/test_display/test_waveplot_ext_axes.png
  tests/baseline_images/test_display/test_waveplot_mono.png
  tests/baseline_images/test_display/test_waveplot_stereo.png
  tests/test_display.py
  tests/test_util.py
Labels: enhancement, functionality

#969 Compat fix: Fix core.load fallback condition
  librosa/core/audio.py
Labels: bug, enhancement

#973 Revert "Compat fix: Fix core.load fallback condition"
  librosa/core/audio.py
Labels: enhancement
