Repository librosa/librosa, pull requests merged in 2019-03, with the labels that each got.

#841 removed realpath from load, fixes #768
  librosa/core/audio.py
Labels: IO

#849 remove one of the two softmask items in the doc
  librosa/util/__init__.py
Labels: documentation

#847 [CR needed] Soundfile-based loader
  .travis_dependencies.sh
  README.md
  docs/ioformats.rst
  librosa/core/audio.py
  setup.py
  tests/data/test1_22050.mp3
  tests/test_core.py
  tests/test_util.py
Labels: IO, enhancement

#853 [FIX] type error in soundfile reading
  librosa/core/audio.py
Labels: bug

#842 [CR needed] Path enhancement
  librosa/filters.py
  librosa/segment.py
  tests/test_filters.py
  tests/test_segment.py
Labels: enhancement, functionality

#852 [CR wanted] ICQT rewrite
  librosa/core/constantq.py
  tests/test_constantq.py
Labels: API change, bug, enhancement

#855 JIT caching for numba functions
  librosa/core/spectrum.py
  librosa/filters.py
  librosa/sequence.py
  librosa/util/matching.py
Labels: enhancement

#797 Add LPC coefficient estimation via Burg's method
  librosa/core/__init__.py
  librosa/core/audio.py
  tests/makeTestData.m
  tests/test_core.py
Labels: enhancement, functionality
