Repository librosa/librosa, pull requests merged in 2019-04, with the labels that each got.

#863 resample type option added in pitch_shift()
  librosa/effects.py
Labels: enhancement

#867 Added ref parameter to piptrack
  librosa/core/pitch.py
  tests/test_core.py
Labels: API change, enhancement, functionality

#859 [CR requested] ICQT resampling mode and polyphase resampling
  .gitignore
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/effects.py
  tests/test_constantq.py
  tests/test_core.py
Labels: API change, enhancement, functionality

#870 fixed #862 and #830, removed deprecations
  docs/cache.rst
  librosa/core/__init__.py
  librosa/feature/__init__.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/version.py
Labels: API change, management

#864 [CR needed] fixed #851 and #816 to add initialization and streaming support to pcen
  docs/examples/plot_pcen_stream.py
  librosa/core/spectrum.py
  tests/test_core.py
Labels: API change, bug, enhancement, functionality
