Repository librosa/librosa, pull requests merged in 2019-05, with the labels that each got.

#844 Feature inversion
  .gitignore
  librosa/core/__init__.py
  librosa/core/spectrum.py
  librosa/feature/__init__.py
  librosa/feature/inverse.py
  librosa/util/__init__.py
  librosa/util/_nnls.py
  tests/test_core.py
  tests/test_features.py
  tests/test_util.py
Labels: functionality

#872 Stream generator
  docs/examples/plot_pcen_stream.py
  docs/ioformats.rst
  librosa/core/__init__.py
  librosa/core/audio.py
  librosa/core/time_frequency.py
  tests/test_core.py
  tests/test_time_frequency.py
Labels: IO, enhancement, functionality

#868 fix: dtw(C=C,subseq=True) doesn't work
  librosa/sequence.py
  tests/test_dtw.py
Labels: bug

#878 Exception error message change, minor PEP8 formatting
  .gitignore
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/fft.py
  librosa/core/spectrum.py
  librosa/effects.py
Labels: enhancement

#884 Minor fix on string 59
  README.md
Labels: documentation

#882 Update docstrings with plot examples
  librosa/beat.py
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/harmonic.py
  librosa/core/spectrum.py
  librosa/core/time_frequency.py
  librosa/decompose.py
  librosa/display.py
  librosa/feature/inverse.py
  librosa/feature/rhythm.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/segment.py
  librosa/sequence.py
  librosa/util/_nnls.py
  librosa/util/utils.py
Labels: documentation

#861 Test LPC with both float32 and float64
  librosa/core/audio.py
  tests/test_core.py
Labels: bug, testing
