Repository librosa/librosa, pull requests merged in 2020-05, with the labels that each got.

#1107 update numba calls for version 0.50.0
  librosa/util/decorators.py
Labels: Upstream/dependency bug

#1059 added SRC samplerate dispatch to resample
  .travis.yml
  .travis_dependencies.sh
  appveyor.yml
  docs/conf.py
  librosa/core/audio.py
  setup.py
  tests/test_core.py
Labels: API change, enhancement

#1110 updating setup and travis for python 3.8
  .travis.yml
  setup.py
Labels: management, testing

#1112 [CR needed] fixed #1111 - revised stack_memory and tests
  .travis.yml
  .travis_dependencies.sh
  librosa/feature/utils.py
  tests/test_features.py
Labels: bug, enhancement, testing

#1118 Fix numba version deprecation warning
  librosa/util/decorators.py
  setup.py
Labels: enhancement

#1123 add python_requires to setup.py
  setup.py
Labels: enhancement, management

#1125 [CR needed] Updates to frame API
  librosa/util/utils.py
  tests/test_util.py
Labels: API change, enhancement

#1127 Update issue templates [ci skip]
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: management

#1131 Tightened requirements on valid_audio
  librosa/util/utils.py
  tests/test_failures.py
Labels: API change, bug

#1134 add B, C, D, Z weightings
  librosa/core/spectrum.py
  librosa/core/time_frequency.py
  tests/test_time_frequency.py
Labels: enhancement, functionality
