Repository librosa/librosa, pull requests merged in 2020-07, with the labels that each got.

#1198 added util.localmin
  librosa/util/__init__.py
  librosa/util/utils.py
  tests/test_util.py
Labels: functionality

#1063 YIN and pYIN
  librosa/core/pitch.py
  tests/data/pitch-pyin.npy
  tests/data/pitch-yin.npy
  tests/test_core.py
Labels: functionality

#1203 [CR] Indian classical support
  librosa/__init__.py
  librosa/core/__init__.py
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/convert.py
  librosa/core/notation.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/display.py
  librosa/feature/spectral.py
  librosa/filters.py
  tests/baseline_images/test_display/test_chroma_svara.png
  tests/baseline_images/test_display/test_coords.png
  tests/baseline_images/test_display/test_cqt_note.png
  tests/baseline_images/test_display/test_display_cqt_svara.png
  tests/test_convert.py
  tests/test_display.py
  tests/test_notation.py
Labels: enhancement, functionality

#1193 Audit for 0.8 release
  AUTHORS.md
  docs/_static/css/custom.css
  docs/changelog.rst
  docs/examples/plot_chroma.py
  docs/examples/plot_display.py
  docs/img/librosa_logo_text.svg
  librosa/__init__.py
  librosa/_cache.py
  librosa/beat.py
  librosa/core/__init__.py
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/convert.py
  librosa/core/fft.py
  librosa/core/harmonic.py
  librosa/core/notation.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/decompose.py
  librosa/display.py
  librosa/effects.py
  librosa/feature/__init__.py
  librosa/feature/inverse.py
  librosa/feature/rhythm.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/segment.py
  librosa/sequence.py
  librosa/util/__init__.py
  librosa/util/_nnls.py
  librosa/util/decorators.py
  librosa/util/deprecation.py
  librosa/util/exceptions.py
  librosa/util/files.py
  librosa/util/matching.py
  librosa/util/utils.py
  librosa/version.py
  setup.py
  tests/test_beat.py
  tests/test_constantq.py
  tests/test_convert.py
  tests/test_core.py
  tests/test_decompose.py
  tests/test_display.py
  tests/test_dtw.py
  tests/test_effects.py
  tests/test_features.py
  tests/test_filters.py
  tests/test_met_features.py
  tests/test_notation.py
  tests/test_onset.py
  tests/test_segment.py
  tests/test_sequence.py
  tests/test_util.py
Labels: documentation

#1211 Update changelog.rst
  docs/changelog.rst
Labels: documentation
