Repository librosa/librosa, pull requests merged in 2020-06, with the labels that each got.

#1140 removed contiguity requirement for audio. fixes #1133
  librosa/util/utils.py
  tests/test_failures.py
Labels: API change, enhancement

#1147 Display doc updates
  librosa/display.py
  tests/test_display.py
Labels: bug, documentation

#1149 Key support for note conversion and display
  librosa/core/time_frequency.py
  librosa/display.py
  tests/test_time_frequency.py
Labels: API change, enhancement, functionality

#1157 Fix hopsize issue for iirt
  librosa/core/spectrum.py
  tests/test_core.py
Labels: bug

#1159 Remove pre-emphasis glitch
  librosa/effects.py
  tests/test_effects.py
Labels: bug, enhancement

#1164 Use Numba API location for jit import.
  librosa/util/decorators.py
Labels: enhancement

#1166 return D_steps for backtracking by user
  librosa/sequence.py
  tests/test_dtw.py
Labels: API change, enhancement, functionality

#1018 [CR] Variable-Q transform
  librosa/core/__init__.py
  librosa/core/constantq.py
  librosa/filters.py
  tests/test_constantq.py
Labels: enhancement, functionality

#1171 [CR] Dtype inference and control in CQT
  librosa/core/constantq.py
  librosa/core/spectrum.py
  librosa/util/__init__.py
  librosa/util/utils.py
  tests/test_constantq.py
  tests/test_util.py
Labels: API change, enhancement

#1175 finished deprecation of old mel normalization behaviors. #1050
  librosa/filters.py
  tests/data/feature-melfbnorm-001.mat
  tests/data/feature-melfbnorm-003.mat
  tests/test_filters.py
Labels: API change

#1179 Only use initialized memory in tests
  tests/test_core.py
  tests/test_decompose.py
  tests/test_features.py
  tests/test_util.py
Labels: testing

#1182 specshow returns quadmesh
  librosa/display.py
Labels: API change

#1183 Chroma and tonnetz updates
  docs/examples/plot_chroma.py
  librosa/feature/spectral.py
  tests/baseline_images/test_display/test_tonnetz.png
  tests/test_features.py
Labels: API change, enhancement, functionality

#1186 cmap returns binary colormaps for boolean data
  librosa/display.py
Labels: enhancement

#1190 Correct dtype usage in griffinlim_cqt
  librosa/core/constantq.py
Labels: bug

#1192 updated default bpo for cens
  librosa/feature/spectral.py
Labels: API change, bug

#1178 Documentation updates and other fixes
  docs/Makefile
  docs/_static/css/custom.css
  docs/_templates/banner.html
  docs/_templates/versions.html
  docs/cache.rst
  docs/changelog.rst
  docs/conf.py
  docs/core.rst
  docs/examples/audio/sir_duke_fast.mp3
  docs/examples/audio/sir_duke_fast.ogg
  docs/examples/audio/sir_duke_slow.mp3
  docs/examples/audio/sir_duke_slow.ogg
  docs/examples/plot_chroma.py
  docs/examples/plot_display.py
  docs/examples/plot_hprss.py
  docs/examples/plot_music_sync.py
  docs/examples/plot_pcen_stream.py
  docs/examples/plot_presets.py
  docs/examples/plot_segmentation.py
  docs/examples/plot_superflux.py
  docs/examples/plot_viterbi.py
  docs/examples/plot_vocal_separation.py
  docs/genindex.rst
  docs/glossary.rst
  docs/img/librosa_logo_text.png
  docs/img/librosa_logo_text.svg
  docs/index.rst
  docs/install.rst
  docs/ioformats.rst
  docs/troubleshooting.rst
  docs/tutorial.rst
  librosa/__init__.py
  librosa/beat.py
  librosa/core/__init__.py
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/fft.py
  librosa/core/harmonic.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/core/time_frequency.py
  librosa/decompose.py
  librosa/display.py
  librosa/effects.py
  librosa/feature/inverse.py
  librosa/feature/rhythm.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/segment.py
  librosa/sequence.py
  librosa/util/_nnls.py
  librosa/util/deprecation.py
  librosa/util/files.py
  librosa/util/matching.py
  librosa/util/utils.py
  setup.py
  tests/test_core.py
Labels: documentation, enhancement, management

#1196 Fix padding for IIRT
  librosa/core/spectrum.py
  tests/test_core.py
Labels: bug
