Repository librosa/librosa, pull requests merged in 2020-01, with the labels that each got.

#1008 add liftering support to MFCC inversion
  librosa/feature/inverse.py
  tests/test_features.py
Labels: enhancement

#1048 add SuperKogito to AUTHORS.md [ci skip]
  AUTHORS.md
Labels: documentation

#1054 length of generated tones
  librosa/core/audio.py
  tests/test_core.py
Labels: bug

#1055 removed dct_type=None from mfcc docs
  librosa/feature/inverse.py
  librosa/feature/spectral.py
Labels: documentation

#1050 Mel filterbank normalization
  librosa/filters.py
  tests/test_filters.py
Labels: API change, documentation

#1031 various DTW bugfixes
  librosa/sequence.py
  tests/test_dtw.py
Labels: bug
