Repository librosa/librosa, pull requests merged in 2021-08, with the labels that each got.

#1355 Multichannel features
  librosa/core/spectrum.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  tests/test_features.py
  tests/test_multichannel.py
Labels: enhancement, functionality, API change

#1372 get_duration function now compatible with int16 and other dtypes
  librosa/core/audio.py
Labels: enhancement

#1371 Multichannel: segment and sequence
  librosa/segment.py
  librosa/sequence.py
  tests/test_dtw.py
  tests/test_segment.py
  tests/test_sequence.py
Labels: enhancement

#1365 Multichannel beat
  librosa/beat.py
  librosa/feature/rhythm.py
  librosa/feature/spectral.py
  librosa/onset.py
  tests/test_multichannel.py
Labels: enhancement, functionality
