Repository librosa/librosa, pull requests merged in 2021-11, with the labels that each got.

#1401 user can control resampling in iirt
  librosa/core/spectrum.py
Labels: enhancement, API change

#1404 Removes unused imports in setup.py & spectral.py
  librosa/feature/spectral.py
  setup.py
Labels: enhancement

#1406 Move responsibility for fetching version number to setup.cfg
  setup.cfg
  setup.py
Labels: management

#1405 [CR] generalizing cqt/vqt filterbank construction
  librosa/core/constantq.py
  librosa/filters.py
  tests/test_constantq.py
  tests/test_filters.py
Labels: enhancement, functionality

#1409 added codecov config
  .github/codecov.yml
Labels: testing, management
