Repository librosa/librosa, pull requests merged in 2021-12, with the labels that each got.

#1410 Removed examples/ folder
  docs/_static/playback-thumbnail.png
  docs/conf.py
  docs/examples/plot_audio_playback.py
  examples/LibROSA audio effects and playback.ipynb
  examples/LibROSA demo.ipynb
  examples/adjust_tuning.py
  examples/beat_tracker.py
  examples/estimate_tuning.py
  examples/hpss.py
  examples/hpss_beats.py
  examples/onset_detector.py
  examples/time_stretch.py
  setup.cfg
Labels: documentation

#1407 [CR] Fixing cqt filterbank normalization
  librosa/core/constantq.py
Labels: bug

#1412 Check for unique frequencies in harmonic interpolation
  librosa/core/harmonic.py
  librosa/util/__init__.py
  librosa/util/utils.py
  tests/test_core.py
  tests/test_util.py
Labels: enhancement, functionality

#1413 optionally disable unicode in specshow
  librosa/display.py
  tests/baseline_images/test_display/test_specshow_unicode_false.png
  tests/baseline_images/test_display/test_specshow_unicode_true.png
  tests/test_display.py
Labels: enhancement

#1414 [CR] specshow coordinate centering
  .github/environment-minimal.yml
  docs/BUILD.md
  docs/examples/plot_display.py
  docs/examples/plot_segmentation.py
  librosa/display.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/segment.py
  librosa/sequence.py
  setup.cfg
  tests/baseline_images/test_display/test_abs_input.png
  tests/baseline_images/test_display/test_chroma.png
  tests/baseline_images/test_display/test_chroma_svara.png
  tests/baseline_images/test_display/test_complex_input.png
  tests/baseline_images/test_display/test_coords.png
  tests/baseline_images/test_display/test_cqt_hz.png
  tests/baseline_images/test_display/test_cqt_note.png
  tests/baseline_images/test_display/test_display_cqt_svara.png
  tests/baseline_images/test_display/test_display_fft_odd.png
  tests/baseline_images/test_display/test_display_fft_svara.png
  tests/baseline_images/test_display/test_display_fourier_tempo_odd.png
  tests/baseline_images/test_display/test_double_chroma.png
  tests/baseline_images/test_display/test_fft_note.png
  tests/baseline_images/test_display/test_fourier_tempo.png
  tests/baseline_images/test_display/test_sharex_specshow_ms.png
  tests/baseline_images/test_display/test_sharex_waveplot_ms.png
  tests/baseline_images/test_display/test_specshow_ext_axes.png
  tests/baseline_images/test_display/test_specshow_unicode_false.png
  tests/baseline_images/test_display/test_specshow_unicode_true.png
  tests/baseline_images/test_display/test_tempo.png
  tests/baseline_images/test_display/test_time_scales_auto.png
  tests/baseline_images/test_display/test_time_unit.png
  tests/baseline_images/test_display/test_time_unit_lag.png
  tests/baseline_images/test_display/test_tonnetz.png
  tests/baseline_images/test_display/test_waveplot_ext_axes.png
  tests/baseline_images/test_display/test_waveplot_mono.png
  tests/baseline_images/test_display/test_waveplot_stereo.png
  tests/baseline_images/test_display/test_waveshow_ext_axes.png
  tests/baseline_images/test_display/test_waveshow_mono.png
  tests/baseline_images/test_display/test_waveshow_mono_zoom.png
  tests/baseline_images/test_display/test_waveshow_mono_zoom_out.png
  tests/baseline_images/test_display/test_waveshow_stereo.png
  tests/baseline_images/test_display/test_x_mel.png
  tests/baseline_images/test_display/test_xaxis_frames_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_lag_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_linear_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_log_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_frames.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_linear.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_log.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_time.png
  tests/baseline_images/test_display/test_xaxis_time_yaxis_lag.png
  tests/baseline_images/test_display/test_xaxis_time_yaxis_none.png
  tests/baseline_images/test_display/test_y_mel.png
  tests/baseline_images/test_display/test_y_mel_bounded.png
  tests/test_display.py
Labels: enhancement

#1418 [CR] add soundfile object handling to load and stream
  .github/environment-ci.yml
  .github/environment-minimal.yml
  librosa/core/audio.py
  tests/test_core.py
Labels: functionality, API change

#1420 Update CI build matrix and dependency versions
  .github/environment-ci.yml
  .github/workflows/ci.yml
  setup.cfg
Labels: testing, management

#1421 0.9.0 deprecation purge
  librosa/display.py
  librosa/util/__init__.py
  librosa/util/files.py
  tests/baseline_images/test_display/test_sharex_specshow_ms.png
  tests/baseline_images/test_display/test_sharex_waveplot_ms.png
  tests/baseline_images/test_display/test_waveplot_ext_axes.png
  tests/baseline_images/test_display/test_waveplot_mono.png
  tests/baseline_images/test_display/test_waveplot_stereo.png
  tests/test_display.py
  tests/test_util.py
Labels: management

#1427 Tiny fix for docstring of `reassigned_spectrogram`
  librosa/core/spectrum.py
Labels: documentation

#1423 Added new examples
  docs/conf.py
  docs/examples/plot_hprss.py
  docs/examples/plot_pcen_stream.py
  docs/examples/plot_vocal_separation.py
  docs/recordings.rst
  librosa/core/audio.py
  librosa/core/harmonic.py
  librosa/core/spectrum.py
  librosa/decompose.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/segment.py
  librosa/sequence.py
  librosa/util/example_data/index.json
  librosa/util/example_data/registry.txt
  tests/test_util.py
Labels: enhancement, documentation

#1428 fixed off-by-one in yin/pyin difference calculation, fixes #1425
  librosa/core/pitch.py
Labels: bug
