Repository librosa/librosa, pull requests merged in 2021-05, with the labels that each got.

#1311 Chromagrams of a signal with n_chroma!=12 & base_c = True
  librosa/filters.py
  tests/test_filters.py
Labels: bug

#1317 CI on github actions
  .coveragerc
  .github/workflows/ci.yml
  .travis.yml
  .travis_dependencies.sh
  README.md
  appveyor.yml
  setup.cfg
  tests/baseline_images/test_display/test_abs_input.png
  tests/baseline_images/test_display/test_chroma.png
  tests/baseline_images/test_display/test_chroma_svara.png
  tests/baseline_images/test_display/test_complex_input.png
  tests/baseline_images/test_display/test_coords.png
  tests/baseline_images/test_display/test_cqt_hz.png
  tests/baseline_images/test_display/test_cqt_note.png
  tests/baseline_images/test_display/test_display_cqt_svara.png
  tests/baseline_images/test_display/test_double_chroma.png
  tests/baseline_images/test_display/test_fourier_tempo.png
  tests/baseline_images/test_display/test_sharex_specshow_ms.png
  tests/baseline_images/test_display/test_sharex_waveplot_ms.png
  tests/baseline_images/test_display/test_specshow_ext_axes.png
  tests/baseline_images/test_display/test_tempo.png
  tests/baseline_images/test_display/test_time_scales_auto.png
  tests/baseline_images/test_display/test_time_unit.png
  tests/baseline_images/test_display/test_time_unit_lag.png
  tests/baseline_images/test_display/test_tonnetz.png
  tests/baseline_images/test_display/test_waveplot_ext_axes.png
  tests/baseline_images/test_display/test_waveplot_mono.png
  tests/baseline_images/test_display/test_waveplot_stereo.png
  tests/baseline_images/test_display/test_x_mel.png
  tests/baseline_images/test_display/test_xaxis_frames_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_lag_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_linear_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_log_yaxis_none.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_frames.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_linear.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_log.png
  tests/baseline_images/test_display/test_xaxis_none_yaxis_time.png
  tests/baseline_images/test_display/test_xaxis_time_yaxis_lag.png
  tests/baseline_images/test_display/test_xaxis_time_yaxis_none.png
  tests/baseline_images/test_display/test_y_mel.png
  tests/baseline_images/test_display/test_y_mel_bounded.png
Labels: management

#1321 Fix parentheses in MFCC liftering docstring
  librosa/feature/inverse.py
  librosa/feature/spectral.py
Labels: documentation

#1322 Make the default hop_length=None for mel_to_audio
  librosa/feature/inverse.py
Labels: bug

#1323 Simplify and strengthen CQT tests
  .gitignore
  tests/test_constantq.py
Labels: enhancement, management

#1218 stft issues with large FFT size
  librosa/core/spectrum.py
Labels: documentation

#1332 fix #1330 - minimal ubuntu dist → 18.04
  .github/workflows/ci.yml
Labels: management

#1326 Adaptive waveplot; waveshow
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/spectrum.py
  librosa/display.py
  tests/baseline_images/test_display/test_time_scales_auto.png
  tests/baseline_images/test_display/test_waveshow_ext_axes.png
  tests/baseline_images/test_display/test_waveshow_mono.png
  tests/baseline_images/test_display/test_waveshow_mono_zoom.png
  tests/baseline_images/test_display/test_waveshow_mono_zoom_out.png
  tests/baseline_images/test_display/test_waveshow_stereo.png
  tests/test_display.py
Labels: enhancement, functionality

#1333 IO issue cleanup
  librosa/core/audio.py
  setup.py
Labels: documentation, management

#1334 Add htk= parameter to specshow
  librosa/display.py
Labels: enhancement

#1335 Support notation in STFT plots
  librosa/display.py
Labels: enhancement

#1336 Stft decoration tests
  librosa/display.py
  tests/baseline_images/test_display/test_display_fft_svara.png
  tests/baseline_images/test_display/test_fft_note.png
  tests/test_display.py
Labels: documentation, enhancement

#1337 0.8.1 release prep
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  AUTHORS.md
  docs/BUILD.md
  docs/changelog.rst
  docs/conf.py
  docs/examples/plot_display.py
  docs/examples/plot_music_sync.py
  docs/examples/plot_vocal_separation.py
  librosa/core/constantq.py
  librosa/display.py
  librosa/effects.py
  librosa/feature/spectral.py
  librosa/filters.py
  librosa/onset.py
  librosa/segment.py
  librosa/sequence.py
  librosa/version.py
  pyproject.toml
  setup.cfg
  setup.py
  tests/test_display.py
Labels: management

#1340 support np.integer wherever we support int
  librosa/core/audio.py
  librosa/core/spectrum.py
  librosa/display.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/sequence.py
Labels: enhancement

#1341 Safe and optional onset envelope normalization
  librosa/onset.py
  tests/test_onset.py
Labels: bug, enhancement

#1338 Add python-soxr resampler
  docs/conf.py
  librosa/core/audio.py
  setup.cfg
  tests/test_core.py
Labels: enhancement

#1339 0.8.1rc2 prep
  AUTHORS.md
  MANIFEST.in
  docs/BUILD.md
  docs/changelog.rst
  librosa/version.py
Labels: management

#1342 0.8.1 final release prep
  README.md
  docs/changelog.rst
  librosa/display.py
  librosa/effects.py
  librosa/version.py
  tests/test_constantq.py
  tests/test_core.py
  tests/test_display.py
  tests/test_effects.py
  tests/test_filters.py
  tests/test_onset.py
Labels: management
