Repository librosa/librosa, pull requests merged in 2021-04, with the labels that each got.

#1298 docs: Fix dim calculation error
  librosa/core/audio.py
Labels: documentation

#1300 display.specshow: fix mel frequency range
  librosa/display.py
Labels: bug

#1308 trying to fix some CI issues
  .travis.yml
  .travis_dependencies.sh
  appveyor.yml
  setup.cfg
  tests/test_display.py
Labels: Upstream/dependency bug, management

#1312 Scale covariance, self-similarity etc. plots to square
  docs/conf.py
  docs/examples/plot_display.py
  librosa/display.py
  tests/test_display.py
Labels: enhancement, functionality
