Repository librosa/librosa, pull requests merged in 2022-09, with the labels that each got.

#1568 off-by-one error in STFT frame padding
  librosa/core/spectrum.py
Labels: bug

#1565 use rfft when appropriate in autocorrelate, fixes #1526
  librosa/core/audio.py
  tests/test_core.py
Labels: enhancement

#1571 forced floating point sampling rates in multirate filterbank
  librosa/filters.py
  tests/test_core.py
Labels: bug

#1574 Improve filter visualization for semitone_filterbank docstring
  librosa/filters.py
Labels: documentation

#1572 vectorized note and svara converters properly
  librosa/core/convert.py
  librosa/util/decorators.py
  tests/test_convert.py
Labels: enhancement, functionality, API change

#1566 Changing default resampler
  .github/environment-ci.yml
  .github/environment-docs.yml
  .github/environment-minimal.yml
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/spectrum.py
  librosa/effects.py
  setup.cfg
  tests/test_constantq.py
  tests/test_core.py
Labels: enhancement, functionality, API change

#1551 Drop use of contextlib2
  .github/environment-ci.yml
  .github/environment-minimal.yml
  librosa/version.py
  setup.cfg
  tests/test_beat.py
  tests/test_effects.py
  tests/test_filters.py
  tests/test_multichannel.py
  tests/test_onset.py
Labels: testing, management

#1577 CI updates, dropping python 3.6
  .github/environment-ci.yml
  .github/environment-docs.yml
  .github/environment-minimal.yml
  .github/workflows/ci.yml
  docs/BUILD.md
  docs/conf.py
  librosa/version.py
  setup.cfg
  tests/test_beat.py
  tests/test_effects.py
  tests/test_filters.py
  tests/test_multichannel.py
  tests/test_onset.py
Labels: documentation, testing, management

#1581 updated tests for numpy 1.23 compatibility
  tests/test_core.py
  tests/test_multichannel.py
  tests/test_util.py
Labels: bug, testing
