Repository librosa/librosa, pull requests merged in 2022-06, with the labels that each got.

#1491 pinned sphinx version to 4.5 for doc site
  .github/environment-docs.yml
Labels: documentation, management

#1493 bug-fix for multichannel splitting
  librosa/effects.py
  tests/test_effects.py
Labels: bug

#1507 Remove redundant article in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1508 Fix typo in warning in inverse.py
  librosa/feature/inverse.py
Labels: enhancement

#1509 Fix multiple typos in spectral.py
  librosa/feature/spectral.py
Labels: enhancement

#1504 Speed up `magphase`
  librosa/core/spectrum.py
  tests/test_core.py
Labels: enhancement

#1511 Escape special characters in the directory paths when calling find_files()
  librosa/util/files.py
Labels: wontfix, documentation, discussion

#1513 Documentation updates ahead of 0.9.2 release
  AUTHORS.md
  docs/changelog.rst
  docs/conf.py
  librosa/effects.py
  librosa/segment.py
  librosa/version.py
Labels: documentation
