Repository librosa/librosa, pull requests merged in 2022-08, with the labels that each got.

#1548 removed hanning from tests, fixes #1547
  tests/test_filters.py
Labels: testing

#1557 updating codespell and corrections
  .github/workflows/lint_python.yml
  librosa/core/audio.py
Labels: testing, management

#1561 High-dimensional resampling, axis targeting
  librosa/core/audio.py
  tests/test_multichannel.py
Labels: enhancement, functionality, API change

#1560 Correct window bandwidth calculation and documentation
  librosa/filters.py
Labels: bug, documentation, API change

#1563 Explain `cmap` in `specshow` docs
  librosa/display.py
Labels: documentation, display
