Repository librosa/librosa, pull requests merged in 2022-07, with the labels that each got.

#1501 Square plots when different axis types are compatible
  librosa/display.py
  tests/test_display.py
Labels: enhancement

#1520 Add instructions for updating test_display images in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1521 0.10 positional argument deprecation removal and dev version bump
  librosa/beat.py
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/convert.py
  librosa/core/harmonic.py
  librosa/core/notation.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/decompose.py
  librosa/display.py
  librosa/effects.py
  librosa/feature/inverse.py
  librosa/feature/rhythm.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/segment.py
  librosa/sequence.py
  librosa/util/decorators.py
  librosa/util/files.py
  librosa/util/utils.py
  librosa/version.py
  tests/test_util.py
Labels: API change

#1485 Support for "h" and "m" in TimeFormatter
  librosa/display.py
  tests/baseline_images/test_display/test_time_unit.png
  tests/baseline_images/test_display/test_time_unit_lag.png
  tests/test_display.py
Labels: functionality

#1514 [CR needed] STFT pre-allocation
  docs/examples/plot_pcen_stream.py
  librosa/core/spectrum.py
  tests/test_core.py
  tests/test_failures.py
Labels: enhancement, functionality

#1529 Accelerated abs2 and phasor
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/spectrum.py
  librosa/feature/spectral.py
  librosa/filters.py
  librosa/util/__init__.py
  librosa/util/utils.py
  tests/test_util.py
Labels: enhancement, functionality

#1535 Standardize integer type checks
  librosa/core/audio.py
  librosa/core/spectrum.py
  librosa/effects.py
  librosa/onset.py
  librosa/sequence.py
  librosa/util/__init__.py
  librosa/util/utils.py
  tests/test_util.py
Labels: enhancement

#1533 Localmax and localmin vectorization
  librosa/util/utils.py
Labels: enhancement

#1536 adds keyword argument definitions to docstrings
  .gitignore
  librosa/feature/inverse.py
  librosa/feature/spectral.py
Labels: documentation

#1539 Refactor AdaptiveWaveplot, disconnection support
  librosa/display.py
  tests/test_display.py
Labels: enhancement, display

#1537 Improve the contributing guide
  .github/environment-ci.yml
  CONTRIBUTING.md
Labels: documentation

#1543 Fixes the PR reference number in the Changelog
  docs/changelog.rst
Labels: documentation

#1545 Fixes docstring for 'note_to_midi' function in librosa/core/convert.py
  librosa/core/convert.py
Labels: documentation
