Repository librosa/librosa, pull requests merged in 2022-01, with the labels that each got.

#1430 Remove unnecessary dynamic __all__ modifications
  librosa/__init__.py
  librosa/core/__init__.py
  librosa/feature/__init__.py
  librosa/util/__init__.py
Labels: management

#1431 [CR] Required kwargs
  docs/examples/plot_audio_playback.py
  docs/examples/plot_superflux.py
  docs/multichannel.rst
  librosa/_cache.py
  librosa/beat.py
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/convert.py
  librosa/core/harmonic.py
  librosa/core/notation.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/decompose.py
  librosa/display.py
  librosa/effects.py
  librosa/feature/inverse.py
  librosa/feature/rhythm.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/segment.py
  librosa/sequence.py
  librosa/util/_nnls.py
  librosa/util/decorators.py
  librosa/util/deprecation.py
  librosa/util/files.py
  librosa/util/utils.py
  tests/test_constantq.py
  tests/test_convert.py
  tests/test_core.py
  tests/test_display.py
  tests/test_effects.py
  tests/test_features.py
  tests/test_filters.py
  tests/test_multichannel.py
  tests/test_sequence.py
  tests/test_util.py
Labels: API change

#1436 Warning stacklevels
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/harmonic.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/display.py
  librosa/feature/inverse.py
  librosa/filters.py
  librosa/util/decorators.py
  librosa/util/deprecation.py
  librosa/util/utils.py
Labels: enhancement, management

#1439 0.9.0rc0 release preparation
  .github/environment-minimal.yml
  .github/workflows/lint_python.yml
  AUTHORS.md
  docs/changelog.rst
  docs/conf.py
  librosa/beat.py
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/convert.py
  librosa/core/harmonic.py
  librosa/core/notation.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/decompose.py
  librosa/display.py
  librosa/effects.py
  librosa/feature/inverse.py
  librosa/feature/rhythm.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/segment.py
  librosa/sequence.py
  librosa/util/_nnls.py
  librosa/util/decorators.py
  librosa/util/deprecation.py
  librosa/util/files.py
  librosa/util/matching.py
  librosa/util/utils.py
  librosa/version.py
Labels: management
