Repository librosa/librosa, pull requests merged in 2022-10, with the labels that each got.

#1579 lazy imports
  MANIFEST.in
  docs/troubleshooting.rst
  librosa/__init__.py
  librosa/__init__.pyi
  librosa/core/__init__.py
  librosa/core/__init__.pyi
  librosa/core/audio.py
  librosa/display.py
  librosa/feature/__init__.py
  librosa/feature/__init__.pyi
  librosa/util/__init__.py
  librosa/util/__init__.pyi
  setup.cfg
Labels: enhancement, blocked

#1586 fixed #1585 figure layout issues [ci skip]
  docs/conf.py
  docs/examples/plot_music_sync.py
Labels: bug, documentation

#1592 Fixed docs badge link
  README.md
Labels: documentation

#1594 Replace numpy deprecated types with python types.
  librosa/util/utils.py
  tests/test_util.py
Labels: enhancement, good for beginners

#1596 harmonic interpolation for scipy 1.9.3
  tests/test_multichannel.py
Labels: bug, testing
