Repository librosa/librosa, pull requests merged in 2022-12, with the labels that each got.

#1614 Improved docs resample
  librosa/core/audio.py
Labels: documentation

#1587 Add type annotations
  .coveragerc
  .github/workflows/lint_python.yml
  MANIFEST.in
  librosa/_cache.py
  librosa/_typing.py
  librosa/beat.py
  librosa/core/__init__.pyi
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/convert.py
  librosa/core/fft.py
  librosa/core/harmonic.py
  librosa/core/intervals.py
  librosa/core/notation.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/decompose.py
  librosa/display.py
  librosa/effects.py
  librosa/feature/__init__.pyi
  librosa/feature/inverse.py
  librosa/feature/rhythm.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/py.typed
  librosa/segment.py
  librosa/sequence.py
  librosa/util/_nnls.py
  librosa/util/decorators.py
  librosa/util/deprecation.py
  librosa/util/files.py
  librosa/util/matching.py
  librosa/util/utils.py
  librosa/version.py
  setup.cfg
  tests/mypy.ini
  tests/test_beat.py
  tests/test_constantq.py
  tests/test_convert.py
  tests/test_core.py
  tests/test_decompose.py
  tests/test_display.py
  tests/test_dtw.py
  tests/test_effects.py
  tests/test_failures.py
  tests/test_filters.py
  tests/test_multichannel.py
  tests/test_onset.py
  tests/test_segment.py
  tests/test_sequence.py
  tests/test_util.py
Labels: enhancement, functionality

#1617 Parabolic interpolation speedup for yin
  .coveragerc
  librosa/core/pitch.py
  tests/test_core.py
Labels: enhancement

#1623 fixed #1618 - updated docstrings
  librosa/display.py
Labels: documentation

#1631 updated cache action to v3
  .github/requirements-lint.txt
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/lint_python.yml
  .github/workflows/publish.yml
Labels: testing, management

#1625 Soundfile exception handling, version bump
  .github/environment-ci.yml
  .github/environment-docs.yml
  .github/environment-minimal.yml
  README.md
  docs/ioformats.rst
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/util/decorators.py
  librosa/util/deprecation.py
  setup.cfg
  tests/test_core.py
  tests/test_util.py
Labels: IO

#1612 Rainbowgram
  docs/examples/plot_rainbowgram.py
Labels: documentation

#1632 [CR] Type annotations continued
  .github/environment-ci.yml
  .github/environment-docs.yml
  .github/environment-lint.yml
  .github/environment-minimal.yml
  .github/requirements-lint.txt
  .github/workflows/lint_python.yml
  librosa/__init__.pyi
  librosa/_cache.py
  librosa/_typing.py
  librosa/beat.py
  librosa/core/__init__.pyi
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/convert.py
  librosa/core/fft.py
  librosa/core/harmonic.py
  librosa/core/intervals.py
  librosa/core/notation.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/decompose.py
  librosa/display.py
  librosa/effects.py
  librosa/feature/__init__.pyi
  librosa/feature/inverse.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/segment.py
  librosa/sequence.py
  librosa/util/__init__.pyi
  librosa/util/_nnls.py
  librosa/util/decorators.py
  librosa/util/files.py
  librosa/util/matching.py
  librosa/util/utils.py
  librosa/version.py
  setup.cfg
  tests/mypy.ini
  tests/test_constantq.py
  tests/test_core.py
  tests/test_decompose.py
  tests/test_display.py
  tests/test_dtw.py
  tests/test_features.py
  tests/test_onset.py
  tests/test_util.py
Labels: enhancement, testing, management
