Repository librosa/librosa, pull requests merged in 2022-04, with the labels that each got.

#1469 Fix db_to_amplitude docs
  librosa/core/spectrum.py
Labels: documentation

#1473 Improved read me
  README.md
Labels: documentation

#1475 Expanded documentation for discriminative viterbi
  .github/environment-minimal.yml
  librosa/sequence.py
Labels: documentation, testing

#1477 Allow preconstructed audioread objects in load
  .github/environment-ci.yml
  .github/environment-minimal.yml
  .github/workflows/ci.yml
  docs/troubleshooting.rst
  librosa/core/audio.py
  setup.cfg
  tests/test_core.py
Labels: functionality, management, IO
