Repository librosa/librosa, pull requests merged in 2023-09, with the labels that each got.

#1739 Multiple accidentals
  AUTHORS.md
  librosa/core/notation.py
  tests/test_notation.py
Labels: enhancement, music theory

#1755 Avoid deprecated matplotlib functions
  librosa/display.py
Labels: bug, display

#1756 Mode support
  docs/examples/plot_display.py
  librosa/core/notation.py
  tests/test_notation.py
Labels: enhancement, functionality, music theory

#1762 Mode support
  docs/examples/plot_display.py
  librosa/core/notation.py
Labels: documentation, music theory
