Repository librosa/librosa, pull requests merged in 2023-10, with the labels that each got.

#1765 Switch from pkg_resources to importlib.resources
  librosa/core/intervals.py
  librosa/util/example_data/__init__.py
  librosa/util/files.py
  setup.cfg
Labels: enhancement

#1769 Add python 3.11 to build matrix
  .github/workflows/ci.yml
  setup.cfg
Labels: testing, management

#1770 Natural accidentals for out-of-key notes
  librosa/core/notation.py
  tests/test_notation.py
Labels: enhancement, music theory
