Repository librosa/librosa, pull requests merged in 2023-02, with the labels that each got.

#1647 f0 harmonic interpolation
  docs/examples/plot_spectral_harmonics.py
  librosa/__init__.py
  librosa/__init__.pyi
  librosa/beat.py
  librosa/core/__init__.pyi
  librosa/core/harmonic.py
  librosa/feature/__init__.py
  librosa/feature/__init__.pyi
  librosa/feature/rhythm.py
  tests/test_beat.py
  tests/test_core.py
  tests/test_features.py
  tests/test_multichannel.py
Labels: enhancement, functionality

#1495 added more options for bandwidth estimation
  librosa/segment.py
  tests/test_segment.py
Labels: functionality

#1652 Allow isolated vertices in bandwidth estimation sometimes
  librosa/segment.py
  tests/test_segment.py
Labels: bug

#1653 0.10.0rc0 release prep
  AUTHORS.md
  docs/changelog.rst
  docs/conf.py
  docs/examples/plot_audio_playback.py
  docs/examples/plot_chroma.py
  docs/examples/plot_display.py
  docs/examples/plot_hprss.py
  docs/examples/plot_music_sync.py
  docs/examples/plot_pcen_stream.py
  docs/examples/plot_presets.py
  docs/examples/plot_rainbowgram.py
  docs/examples/plot_segmentation.py
  docs/examples/plot_superflux.py
  docs/examples/plot_viterbi.py
  docs/examples/plot_vocal_separation.py
  docs/troubleshooting.rst
  librosa/_cache.py
  librosa/beat.py
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/convert.py
  librosa/core/harmonic.py
  librosa/core/notation.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/decompose.py
  librosa/display.py
  librosa/effects.py
  librosa/feature/rhythm.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/segment.py
  librosa/sequence.py
  librosa/util/files.py
  librosa/util/utils.py
  librosa/version.py
Labels: documentation, management

#1657 updated doc build targets
  docs/conf.py
Labels: documentation, management

#1660 Doc build headaches continued
  .github/workflows/docs.yml
Labels: documentation

#1661 Doc build continues
  docs/conf.py
Labels: documentation

#1664 reverting mpl version change for doc build
  .github/environment-docs.yml
Labels: documentation

#1665 allow dtype specification in abs2, rms
  librosa/feature/spectral.py
  librosa/util/utils.py
  tests/test_util.py
Labels: bug, enhancement, functionality

#1666 0.10.0rc1
  .github/environment-ci.yml
  .github/environment-docs.yml
  .github/environment-minimal.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .zenodo.json
  AUTHORS.md
  README.md
  docs/changelog.rst
  librosa/version.py
  scripts/create_author_list.py
  setup.cfg
  tests/baseline_images/test_display/test_specshow_chromafjs.png
  tests/baseline_images/test_display/test_specshow_vqt.png
  tests/test_display.py
Labels: documentation, management

#1670 pinning sphinx version for doc environment until we fix jquery issue
  .github/environment-docs.yml
  docs/changelog.rst
  librosa/version.py
  setup.cfg
Labels: documentation, management

#1673 fixed mel_to_stft example, resolves #1672
  librosa/feature/inverse.py
Labels: documentation
