Repository librosa/librosa, pull requests merged in 2023-06, with the labels that each got.

#1713 Several small documentation updates
  .github/workflows/docs.yml
  docs/BUILD.md
  docs/conf.py
  librosa/beat.py
  librosa/core/spectrum.py
  librosa/feature/inverse.py
  librosa/feature/spectral.py
  scripts/get_latest_release.sh
Labels: documentation

#1714 pin numpy version to < 1.24 in doc environment
  .github/environment-docs.yml
Labels: documentation

#1706 README.md typo fix
  README.md
Labels: documentation

#1718 CI for documentation builds
  .github/environment-lint.yml
  .github/workflows/docs-ci.yml
  .github/workflows/lint_python.yml
  CONTRIBUTING.md
  docs/cache.rst
  docs/changelog.rst
  docs/conf.py
  docs/examples/plot_chroma.py
  docs/examples/plot_hprss.py
  docs/examples/plot_segmentation.py
  docs/examples/plot_superflux.py
  docs/examples/plot_vocal_separation.py
  docs/index.rst
  docs/ioformats.rst
  librosa/_cache.py
  librosa/_typing.py
  librosa/beat.py
  librosa/core/__init__.py
  librosa/core/audio.py
  librosa/core/constantq.py
  librosa/core/convert.py
  librosa/core/fft.py
  librosa/core/harmonic.py
  librosa/core/intervals.py
  librosa/core/notation.py
  librosa/core/pitch.py
  librosa/core/spectrum.py
  librosa/decompose.py
  librosa/display.py
  librosa/effects.py
  librosa/feature/inverse.py
  librosa/feature/rhythm.py
  librosa/feature/spectral.py
  librosa/feature/utils.py
  librosa/filters.py
  librosa/onset.py
  librosa/segment.py
  librosa/sequence.py
  librosa/util/__init__.py
  librosa/util/_nnls.py
  librosa/util/decorators.py
  librosa/util/deprecation.py
  librosa/util/files.py
  librosa/util/matching.py
  librosa/util/utils.py
  librosa/version.py
  setup.cfg
Labels: documentation, testing, management

#1719 Advanced example for patch generation
  docs/examples/plot_patch_generation.py
Labels: documentation

#1727 support pooch >= 1.7
  .github/environment-ci.yml
  librosa/util/example_data/index.json
  librosa/util/example_data/registry.txt
  setup.cfg
Labels: management, Upstream/dependency bug

#1726 Consistent conversion of time duration/offset to sample counts
  librosa/core/audio.py
  tests/test_core.py
Labels: enhancement
