Repository librosa/librosa, pull requests merged in 2023-01, with the labels that each got.

#1640 Require matplotlib 3.3+
  .github/requirements-lint.txt
  librosa/display.py
  setup.cfg
Labels: management

#1638 Update LICENSE.md
  LICENSE.md
  docs/conf.py
Labels: documentation

#1643 Zero crossings rewrite
  librosa/core/audio.py
  librosa/feature/spectral.py
  tests/test_core.py
Labels: enhancement, API change

#1645 rebuild lint environment cache
  .github/workflows/lint_python.yml
Labels: testing, management

#1637 Minor typing improvements
  .github/environment-ci.yml
  .github/environment-docs.yml
  .github/environment-minimal.yml
  librosa/_typing.py
  librosa/core/constantq.py
  librosa/decompose.py
  librosa/feature/spectral.py
  librosa/filters.py
  setup.cfg
  tests/test_filters.py
Labels: enhancement

#1646 Vertical waveshow
  librosa/display.py
  tests/baseline_images/test_display/test_waveshow_mono_trans.png
  tests/baseline_images/test_display/test_waveshow_mono_zoom_trans.png
  tests/test_display.py
Labels: enhancement, functionality, display
