Repository librosa/librosa, pull requests merged in 2024-03, with the labels that each got.

#1813 Resolve the performance issue of autocorrelate
  librosa/core/audio.py
Labels: enhancement

#1814 Correct phase advance for odd frame lengths in phase_vocoder
  librosa/core/spectrum.py
Labels: bug

#1766 Multichannel peak, onset, and beat detection
  docs/examples/audio/README.md
  docs/examples/audio/snare-accelerate.ogg
  docs/examples/plot_dynamic_beat.py
  docs/multichannel.rst
  librosa/beat.py
  librosa/onset.py
  librosa/util/utils.py
  tests/baseline_images/test_display/test_coords.png
  tests/test_beat.py
  tests/test_multichannel.py
  tests/test_onset.py
  tests/test_util.py
Labels: enhancement, functionality

#1820 Update actions for 2024
  .github/workflows/ci.yml
  .github/workflows/docs-ci.yml
  .github/workflows/docs.yml
  .github/workflows/lint_python.yml
  .github/workflows/publish.yml
  docs/cache.rst
  docs/examples/plot_pcen_stream.py
  librosa/feature/spectral.py
  scripts/create_author_list.py
Labels: testing, management

#1821 doc copybutton, CI updates
  .github/environment-docs.yml
  .github/workflows/docs-ci.yml
  docs/conf.py
  setup.cfg
Labels: documentation, management

#1822 exposed tempo min and max parameters in specshow
  librosa/display.py
Labels: enhancement, display

#1826 remove kwargs from effects.hpss and friends, passthru stft
  librosa/effects.py
Labels: enhancement, documentation
