Repository librosa/librosa, pull requests merged in 2025-01, with the labels that each got.

#1891 Update effects.py
  librosa/effects.py
Labels: documentation

#1899 allow skipping linkchecks on ~dpwe
  docs/conf.py
Labels: documentation, management

#1900 fixed pooch registry regression from #1829
  librosa/util/example_data/registry.txt
Labels: bug, management

#1903 Modernize for 2024/5
  librosa/core/intervals.py
  librosa/util/files.py
  librosa/util/matching.py
  tests/test_core.py
  tests/test_features.py
Labels: enhancement, management
